---
title: "Problem Set 3"
author: "ylelkes"
date: "September 19, 2015"
output: pdf_document
---

1. Download and install a latex distribution onto your home computer. You will need a different distribution depending on whether you have a mac or a pc. Using it will be optional in this problem set, but we will you start using it next week. 

2. Complete your problem set in markdown. Have different section headings to make it look nicer, as below:

## Immigrant attitudes

### Values

In the data folder on the course website there is a file called immigrantattitudes.RData, which is a survey of immigrants and native Dutch residents on various issues. The codebook is also in that folder.

* Recode the variable that indicates the respondents country of origin wtih country names. Maybe with car::recode.

* Recode ka13a109 with the value labels listed in the code book.

* Create a barplot that is facetted by country of origin, and plot the percentage that chose each value as their first choice. Make sure that there are no NAs. The following code will help, but make sure you understand what it is doing. 

```
geom_bar(aes(y = ..density..,group = ka13a109)) +   scale_y_continuous(labels = percent_format())
```

Also, rotate the x-labels so that they're not on top of each other. Change the theme using ggthemes or ggthemr. Give it a title and print it into your file. Have it echo your code as well.

###
Let's create some scales from some of the items about attitudes about the proper role of men and women using items: ka13a112 - ka13a118. Use rowMeans to create a scale that averages these items into one scale that ranges from 1=Traditional values (woman at home) to 5 (Man at home). Therefore some of the items will need to be recoded.

* Let's look at the reliability of the scale with psych::alpha. 
* Create an object that holds the results of that function.
* First take a look at objectname$key to see if anything needs to be reversed. 
* Next, write up the results from objectname$total. In regular prose with inline R code, report the std.alpha, mean, and sd. Use the round function to limit the number of digits to two. 
* Regress that attitude scale on immigrant group, i.e.,
$traditionalvalues=Turkish+Moroccan+...$ and create a new object
* Next regress net household income on demographic groups and create a new object
* Next regress on feelings towards Geert Wilders, again create a new object.
* Finally, with a logit model, regress a variable that is coded 1 if a person voted in 2012, 0 otherwise on immigrant group, this time include a few other demographics, e.g., education, age. 
* Put all these regression objects into an texreg::htmlreg table. Label all the model names and covariate names, add a table. 
* Finally, write up the results of the table as you would in an article. Use inline r code to extract coefficients, standard errors, and p-values.  